version: '3.9'


include:
  - proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.5
    depends_on:
      - db



  db:
    image: mysql:8
    env_file: ".env"
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10


